# Generated by Django 2.1 on 2018-08-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.CharField(db_index=True, default='74821e5e9f3f11e88206b79ed662db35', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
