# Generated by Django 2.1 on 2018-08-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.CharField(db_index=True, default='b5f3ee88a32e11e8bcc87fa34c60b1da', max_length=255,
                                   primary_key=True, serialize=False, unique=True),
        ),
    ]
