# Generated by Django 2.1 on 2018-08-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.CharField(db_index=True, default='855a02ae982411e89383c569513f40c7', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
