# Generated by Django 2.1 on 2018-09-09 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosineSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.FloatField(default=0)),
                ('album', models.FloatField(default=0)),
                ('artist', models.FloatField(default=0)),
                ('songBase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CosineSimilarity_right', to='songs.Song')),
                ('songCompare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CosineSimilarity_left', to='songs.Song')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cosinesimilarity',
            unique_together={('songBase', 'songCompare')},
        ),
    ]
