# Generated by Django 2.1 on 2018-08-18 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosinesimilarity',
            name='songBase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CosineSimilarity_right', to='songs.Song'),
        ),
        migrations.AlterField(
            model_name='cosinesimilarity',
            name='songCompare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CosineSimilarity_left', to='songs.Song'),
        ),
    ]
