from setuptools import setup

setup(
    name='Ouvido Musical Back-end',
    version='3.0',
    packages=['apps', 'apps.kemures', 'apps.kemures.metrics', 'apps.kemures.metrics.MAP',
              'apps.kemures.metrics.MAP.DAO', 'apps.kemures.metrics.MAP.DAO.migrations',
              'apps.kemures.metrics.MAP.runtime', 'apps.kemures.metrics.MAP.runtime.migrations',
              'apps.kemures.metrics.MRR', 'apps.kemures.metrics.MRR.DAO', 'apps.kemures.metrics.MRR.DAO.migrations',
              'apps.kemures.metrics.MRR.runtime', 'apps.kemures.metrics.MRR.runtime.migrations',
              'apps.kemures.metrics.NDCG', 'apps.kemures.metrics.NDCG.DAO', 'apps.kemures.metrics.NDCG.DAO.migrations',
              'apps.kemures.metrics.NDCG.runtime', 'apps.kemures.metrics.NDCG.runtime.migrations',
              'apps.kemures.recommenders', 'apps.kemures.recommenders.UserAverage',
              'apps.kemures.recommenders.UserAverage.DAO', 'apps.kemures.recommenders.UserAverage.DAO.migrations',
              'apps.kemures.recommenders.UserAverage.runtime',
              'apps.kemures.recommenders.UserAverage.runtime.migrations', 'apps.kemures.similarities',
              'apps.kemures.similarities.Cosine', 'apps.kemures.similarities.Cosine.DAO',
              'apps.kemures.similarities.Cosine.DAO.migrations', 'apps.kemures.similarities.Cosine.runtime',
              'apps.kemures.similarities.Cosine.runtime.migrations', 'apps.kemures.kernel_config',
              'apps.kemures.analysis_of_recommendations', 'apps.tecnics', 'apps.tecnics.content_based_metadata',
              'apps.tecnics.content_based_metadata.migrations', 'apps.metadata', 'apps.metadata.songs',
              'apps.metadata.songs.migrations', 'apps.metadata.users', 'apps.metadata.users.migrations',
              'apps.metadata.user_preferences', 'apps.metadata.user_preferences.migrations',
              'venv.lib.python3.6.distutils', 'venv.lib.python3.6.encodings', 'venv.lib.python3.6.importlib',
              'venv.lib.python3.6.collections', 'venv.lib.python3.6.site-packages.pip',
              'venv.lib.python3.6.site-packages.pip._vendor', 'venv.lib.python3.6.site-packages.pip._vendor.idna',
              'venv.lib.python3.6.site-packages.pip._vendor.pytoml',
              'venv.lib.python3.6.site-packages.pip._vendor.certifi',
              'venv.lib.python3.6.site-packages.pip._vendor.chardet',
              'venv.lib.python3.6.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python3.6.site-packages.pip._vendor.distlib',
              'venv.lib.python3.6.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.6.site-packages.pip._vendor.msgpack',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.pip._vendor.colorama',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.6.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.6.site-packages.pip._vendor.progress',
              'venv.lib.python3.6.site-packages.pip._vendor.requests',
              'venv.lib.python3.6.site-packages.pip._vendor.packaging',
              'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.6.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.6.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.6.site-packages.pip._internal', 'venv.lib.python3.6.site-packages.pip._internal.req',
              'venv.lib.python3.6.site-packages.pip._internal.vcs',
              'venv.lib.python3.6.site-packages.pip._internal.utils',
              'venv.lib.python3.6.site-packages.pip._internal.models',
              'venv.lib.python3.6.site-packages.pip._internal.commands',
              'venv.lib.python3.6.site-packages.pip._internal.operations', 'venv.lib.python3.6.site-packages.jedi',
              'venv.lib.python3.6.site-packages.jedi.api', 'venv.lib.python3.6.site-packages.jedi.common',
              'venv.lib.python3.6.site-packages.jedi.evaluate',
              'venv.lib.python3.6.site-packages.jedi.evaluate.context',
              'venv.lib.python3.6.site-packages.jedi.evaluate.compiled',
              'venv.lib.python3.6.site-packages.jedi.evaluate.compiled.subprocess',
              'venv.lib.python3.6.site-packages.nltk', 'venv.lib.python3.6.site-packages.nltk.app',
              'venv.lib.python3.6.site-packages.nltk.ccg', 'venv.lib.python3.6.site-packages.nltk.sem',
              'venv.lib.python3.6.site-packages.nltk.tag', 'venv.lib.python3.6.site-packages.nltk.tbl',
              'venv.lib.python3.6.site-packages.nltk.chat', 'venv.lib.python3.6.site-packages.nltk.draw',
              'venv.lib.python3.6.site-packages.nltk.misc', 'venv.lib.python3.6.site-packages.nltk.stem',
              'venv.lib.python3.6.site-packages.nltk.test', 'venv.lib.python3.6.site-packages.nltk.test.unit',
              'venv.lib.python3.6.site-packages.nltk.test.unit.translate',
              'venv.lib.python3.6.site-packages.nltk.chunk', 'venv.lib.python3.6.site-packages.nltk.parse',
              'venv.lib.python3.6.site-packages.nltk.corpus', 'venv.lib.python3.6.site-packages.nltk.corpus.reader',
              'venv.lib.python3.6.site-packages.nltk.cluster', 'venv.lib.python3.6.site-packages.nltk.metrics',
              'venv.lib.python3.6.site-packages.nltk.twitter', 'venv.lib.python3.6.site-packages.nltk.classify',
              'venv.lib.python3.6.site-packages.nltk.tokenize', 'venv.lib.python3.6.site-packages.nltk.inference',
              'venv.lib.python3.6.site-packages.nltk.sentiment', 'venv.lib.python3.6.site-packages.nltk.translate',
              'venv.lib.python3.6.site-packages.pytz', 'venv.lib.python3.6.site-packages.numpy',
              'venv.lib.python3.6.site-packages.numpy.ma', 'venv.lib.python3.6.site-packages.numpy.ma.tests',
              'venv.lib.python3.6.site-packages.numpy.doc', 'venv.lib.python3.6.site-packages.numpy.fft',
              'venv.lib.python3.6.site-packages.numpy.fft.tests', 'venv.lib.python3.6.site-packages.numpy.lib',
              'venv.lib.python3.6.site-packages.numpy.lib.tests', 'venv.lib.python3.6.site-packages.numpy.core',
              'venv.lib.python3.6.site-packages.numpy.core.tests', 'venv.lib.python3.6.site-packages.numpy.f2py',
              'venv.lib.python3.6.site-packages.numpy.f2py.tests', 'venv.lib.python3.6.site-packages.numpy.tests',
              'venv.lib.python3.6.site-packages.numpy.compat', 'venv.lib.python3.6.site-packages.numpy.compat.tests',
              'venv.lib.python3.6.site-packages.numpy.linalg', 'venv.lib.python3.6.site-packages.numpy.linalg.tests',
              'venv.lib.python3.6.site-packages.numpy.random', 'venv.lib.python3.6.site-packages.numpy.random.tests',
              'venv.lib.python3.6.site-packages.numpy.testing', 'venv.lib.python3.6.site-packages.numpy.testing.tests',
              'venv.lib.python3.6.site-packages.numpy.testing._private',
              'venv.lib.python3.6.site-packages.numpy.distutils',
              'venv.lib.python3.6.site-packages.numpy.distutils.tests',
              'venv.lib.python3.6.site-packages.numpy.distutils.command',
              'venv.lib.python3.6.site-packages.numpy.distutils.fcompiler',
              'venv.lib.python3.6.site-packages.numpy.matrixlib',
              'venv.lib.python3.6.site-packages.numpy.matrixlib.tests',
              'venv.lib.python3.6.site-packages.numpy.polynomial',
              'venv.lib.python3.6.site-packages.numpy.polynomial.tests', 'venv.lib.python3.6.site-packages.parso',
              'venv.lib.python3.6.site-packages.parso.pgen2', 'venv.lib.python3.6.site-packages.parso.python',
              'venv.lib.python3.6.site-packages.scipy', 'venv.lib.python3.6.site-packages.scipy.io',
              'venv.lib.python3.6.site-packages.scipy.io.arff', 'venv.lib.python3.6.site-packages.scipy.io.arff.tests',
              'venv.lib.python3.6.site-packages.scipy.io.tests', 'venv.lib.python3.6.site-packages.scipy.io.matlab',
              'venv.lib.python3.6.site-packages.scipy.io.matlab.tests',
              'venv.lib.python3.6.site-packages.scipy.io.harwell_boeing',
              'venv.lib.python3.6.site-packages.scipy.io.harwell_boeing.tests',
              'venv.lib.python3.6.site-packages.scipy.odr', 'venv.lib.python3.6.site-packages.scipy.odr.tests',
              'venv.lib.python3.6.site-packages.scipy._lib', 'venv.lib.python3.6.site-packages.scipy._lib.tests',
              'venv.lib.python3.6.site-packages.scipy.misc', 'venv.lib.python3.6.site-packages.scipy.misc.tests',
              'venv.lib.python3.6.site-packages.scipy.stats', 'venv.lib.python3.6.site-packages.scipy.stats.tests',
              'venv.lib.python3.6.site-packages.scipy.linalg', 'venv.lib.python3.6.site-packages.scipy.linalg.tests',
              'venv.lib.python3.6.site-packages.scipy.signal', 'venv.lib.python3.6.site-packages.scipy.signal.tests',
              'venv.lib.python3.6.site-packages.scipy.signal.windows', 'venv.lib.python3.6.site-packages.scipy.sparse',
              'venv.lib.python3.6.site-packages.scipy.sparse.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.arpack',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.dsolve',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.dsolve.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.isolve',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.isolve.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.csgraph',
              'venv.lib.python3.6.site-packages.scipy.sparse.csgraph.tests',
              'venv.lib.python3.6.site-packages.scipy.cluster', 'venv.lib.python3.6.site-packages.scipy.cluster.tests',
              'venv.lib.python3.6.site-packages.scipy.fftpack', 'venv.lib.python3.6.site-packages.scipy.fftpack.tests',
              'venv.lib.python3.6.site-packages.scipy.ndimage', 'venv.lib.python3.6.site-packages.scipy.ndimage.tests',
              'venv.lib.python3.6.site-packages.scipy.spatial', 'venv.lib.python3.6.site-packages.scipy.spatial.tests',
              'venv.lib.python3.6.site-packages.scipy.special', 'venv.lib.python3.6.site-packages.scipy.special.tests',
              'venv.lib.python3.6.site-packages.scipy.special._precompute',
              'venv.lib.python3.6.site-packages.scipy.optimize', 'venv.lib.python3.6.site-packages.scipy.optimize._lsq',
              'venv.lib.python3.6.site-packages.scipy.optimize.tests',
              'venv.lib.python3.6.site-packages.scipy.optimize._trlib',
              'venv.lib.python3.6.site-packages.scipy.optimize._trustregion_constr',
              'venv.lib.python3.6.site-packages.scipy.optimize._trustregion_constr.tests',
              'venv.lib.python3.6.site-packages.scipy.constants',
              'venv.lib.python3.6.site-packages.scipy.constants.tests',
              'venv.lib.python3.6.site-packages.scipy.integrate',
              'venv.lib.python3.6.site-packages.scipy.integrate._ivp',
              'venv.lib.python3.6.site-packages.scipy.integrate.tests',
              'venv.lib.python3.6.site-packages.scipy.interpolate',
              'venv.lib.python3.6.site-packages.scipy.interpolate.tests',
              'venv.lib.python3.6.site-packages.scipy._build_utils', 'venv.lib.python3.6.site-packages.wheel',
              'venv.lib.python3.6.site-packages.wheel.tool', 'venv.lib.python3.6.site-packages.wheel.signatures',
              'venv.lib.python3.6.site-packages.django', 'venv.lib.python3.6.site-packages.django.db',
              'venv.lib.python3.6.site-packages.django.db.models',
              'venv.lib.python3.6.site-packages.django.db.models.sql',
              'venv.lib.python3.6.site-packages.django.db.models.fields',
              'venv.lib.python3.6.site-packages.django.db.models.functions',
              'venv.lib.python3.6.site-packages.django.db.backends',
              'venv.lib.python3.6.site-packages.django.db.backends.base',
              'venv.lib.python3.6.site-packages.django.db.backends.dummy',
              'venv.lib.python3.6.site-packages.django.db.backends.mysql',
              'venv.lib.python3.6.site-packages.django.db.backends.oracle',
              'venv.lib.python3.6.site-packages.django.db.backends.sqlite3',
              'venv.lib.python3.6.site-packages.django.db.backends.postgresql',
              'venv.lib.python3.6.site-packages.django.db.backends.postgresql_psycopg2',
              'venv.lib.python3.6.site-packages.django.db.migrations',
              'venv.lib.python3.6.site-packages.django.db.migrations.operations',
              'venv.lib.python3.6.site-packages.django.apps', 'venv.lib.python3.6.site-packages.django.conf',
              'venv.lib.python3.6.site-packages.django.conf.urls',
              'venv.lib.python3.6.site-packages.django.conf.locale',
              'venv.lib.python3.6.site-packages.django.conf.locale.ar',
              'venv.lib.python3.6.site-packages.django.conf.locale.az',
              'venv.lib.python3.6.site-packages.django.conf.locale.bg',
              'venv.lib.python3.6.site-packages.django.conf.locale.bn',
              'venv.lib.python3.6.site-packages.django.conf.locale.bs',
              'venv.lib.python3.6.site-packages.django.conf.locale.ca',
              'venv.lib.python3.6.site-packages.django.conf.locale.cs',
              'venv.lib.python3.6.site-packages.django.conf.locale.cy',
              'venv.lib.python3.6.site-packages.django.conf.locale.da',
              'venv.lib.python3.6.site-packages.django.conf.locale.de',
              'venv.lib.python3.6.site-packages.django.conf.locale.el',
              'venv.lib.python3.6.site-packages.django.conf.locale.en',
              'venv.lib.python3.6.site-packages.django.conf.locale.eo',
              'venv.lib.python3.6.site-packages.django.conf.locale.es',
              'venv.lib.python3.6.site-packages.django.conf.locale.et',
              'venv.lib.python3.6.site-packages.django.conf.locale.eu',
              'venv.lib.python3.6.site-packages.django.conf.locale.fa',
              'venv.lib.python3.6.site-packages.django.conf.locale.fi',
              'venv.lib.python3.6.site-packages.django.conf.locale.fr',
              'venv.lib.python3.6.site-packages.django.conf.locale.fy',
              'venv.lib.python3.6.site-packages.django.conf.locale.ga',
              'venv.lib.python3.6.site-packages.django.conf.locale.gd',
              'venv.lib.python3.6.site-packages.django.conf.locale.gl',
              'venv.lib.python3.6.site-packages.django.conf.locale.he',
              'venv.lib.python3.6.site-packages.django.conf.locale.hi',
              'venv.lib.python3.6.site-packages.django.conf.locale.hr',
              'venv.lib.python3.6.site-packages.django.conf.locale.hu',
              'venv.lib.python3.6.site-packages.django.conf.locale.id',
              'venv.lib.python3.6.site-packages.django.conf.locale.is',
              'venv.lib.python3.6.site-packages.django.conf.locale.it',
              'venv.lib.python3.6.site-packages.django.conf.locale.ja',
              'venv.lib.python3.6.site-packages.django.conf.locale.ka',
              'venv.lib.python3.6.site-packages.django.conf.locale.km',
              'venv.lib.python3.6.site-packages.django.conf.locale.kn',
              'venv.lib.python3.6.site-packages.django.conf.locale.ko',
              'venv.lib.python3.6.site-packages.django.conf.locale.lt',
              'venv.lib.python3.6.site-packages.django.conf.locale.lv',
              'venv.lib.python3.6.site-packages.django.conf.locale.mk',
              'venv.lib.python3.6.site-packages.django.conf.locale.ml',
              'venv.lib.python3.6.site-packages.django.conf.locale.mn',
              'venv.lib.python3.6.site-packages.django.conf.locale.nb',
              'venv.lib.python3.6.site-packages.django.conf.locale.nl',
              'venv.lib.python3.6.site-packages.django.conf.locale.nn',
              'venv.lib.python3.6.site-packages.django.conf.locale.pl',
              'venv.lib.python3.6.site-packages.django.conf.locale.pt',
              'venv.lib.python3.6.site-packages.django.conf.locale.ro',
              'venv.lib.python3.6.site-packages.django.conf.locale.ru',
              'venv.lib.python3.6.site-packages.django.conf.locale.sk',
              'venv.lib.python3.6.site-packages.django.conf.locale.sl',
              'venv.lib.python3.6.site-packages.django.conf.locale.sq',
              'venv.lib.python3.6.site-packages.django.conf.locale.sr',
              'venv.lib.python3.6.site-packages.django.conf.locale.sv',
              'venv.lib.python3.6.site-packages.django.conf.locale.ta',
              'venv.lib.python3.6.site-packages.django.conf.locale.te',
              'venv.lib.python3.6.site-packages.django.conf.locale.th',
              'venv.lib.python3.6.site-packages.django.conf.locale.tr',
              'venv.lib.python3.6.site-packages.django.conf.locale.uk',
              'venv.lib.python3.6.site-packages.django.conf.locale.vi',
              'venv.lib.python3.6.site-packages.django.conf.locale.de_CH',
              'venv.lib.python3.6.site-packages.django.conf.locale.en_AU',
              'venv.lib.python3.6.site-packages.django.conf.locale.en_GB',
              'venv.lib.python3.6.site-packages.django.conf.locale.es_AR',
              'venv.lib.python3.6.site-packages.django.conf.locale.es_CO',
              'venv.lib.python3.6.site-packages.django.conf.locale.es_MX',
              'venv.lib.python3.6.site-packages.django.conf.locale.es_NI',
              'venv.lib.python3.6.site-packages.django.conf.locale.es_PR',
              'venv.lib.python3.6.site-packages.django.conf.locale.pt_BR',
              'venv.lib.python3.6.site-packages.django.conf.locale.sr_Latn',
              'venv.lib.python3.6.site-packages.django.conf.locale.zh_Hans',
              'venv.lib.python3.6.site-packages.django.conf.locale.zh_Hant',
              'venv.lib.python3.6.site-packages.django.core', 'venv.lib.python3.6.site-packages.django.core.mail',
              'venv.lib.python3.6.site-packages.django.core.mail.backends',
              'venv.lib.python3.6.site-packages.django.core.cache',
              'venv.lib.python3.6.site-packages.django.core.cache.backends',
              'venv.lib.python3.6.site-packages.django.core.files',
              'venv.lib.python3.6.site-packages.django.core.checks',
              'venv.lib.python3.6.site-packages.django.core.checks.security',
              'venv.lib.python3.6.site-packages.django.core.checks.compatibility',
              'venv.lib.python3.6.site-packages.django.core.servers',
              'venv.lib.python3.6.site-packages.django.core.handlers',
              'venv.lib.python3.6.site-packages.django.core.management',
              'venv.lib.python3.6.site-packages.django.core.serializers',
              'venv.lib.python3.6.site-packages.django.http', 'venv.lib.python3.6.site-packages.django.test',
              'venv.lib.python3.6.site-packages.django.urls', 'venv.lib.python3.6.site-packages.django.forms',
              'venv.lib.python3.6.site-packages.django.utils',
              'venv.lib.python3.6.site-packages.django.utils.translation',
              'venv.lib.python3.6.site-packages.django.views', 'venv.lib.python3.6.site-packages.django.views.generic',
              'venv.lib.python3.6.site-packages.django.views.decorators',
              'venv.lib.python3.6.site-packages.django.contrib', 'venv.lib.python3.6.site-packages.django.contrib.gis',
              'venv.lib.python3.6.site-packages.django.contrib.gis.db',
              'venv.lib.python3.6.site-packages.django.contrib.gis.db.models',
              'venv.lib.python3.6.site-packages.django.contrib.gis.db.models.sql',
              'venv.lib.python3.6.site-packages.django.contrib.gis.db.backends',
              'venv.lib.python3.6.site-packages.django.contrib.gis.db.backends.base',
              'venv.lib.python3.6.site-packages.django.contrib.gis.db.backends.mysql',
              'venv.lib.python3.6.site-packages.django.contrib.gis.db.backends.oracle',
              'venv.lib.python3.6.site-packages.django.contrib.gis.db.backends.postgis',
              'venv.lib.python3.6.site-packages.django.contrib.gis.db.backends.spatialite',
              'venv.lib.python3.6.site-packages.django.contrib.gis.gdal',
              'venv.lib.python3.6.site-packages.django.contrib.gis.gdal.raster',
              'venv.lib.python3.6.site-packages.django.contrib.gis.gdal.prototypes',
              'venv.lib.python3.6.site-packages.django.contrib.gis.geos',
              'venv.lib.python3.6.site-packages.django.contrib.gis.geos.prototypes',
              'venv.lib.python3.6.site-packages.django.contrib.gis.admin',
              'venv.lib.python3.6.site-packages.django.contrib.gis.forms',
              'venv.lib.python3.6.site-packages.django.contrib.gis.utils',
              'venv.lib.python3.6.site-packages.django.contrib.gis.geoip2',
              'venv.lib.python3.6.site-packages.django.contrib.gis.sitemaps',
              'venv.lib.python3.6.site-packages.django.contrib.gis.serializers',
              'venv.lib.python3.6.site-packages.django.contrib.auth',
              'venv.lib.python3.6.site-packages.django.contrib.auth.handlers',
              'venv.lib.python3.6.site-packages.django.contrib.auth.management',
              'venv.lib.python3.6.site-packages.django.contrib.auth.migrations',
              'venv.lib.python3.6.site-packages.django.contrib.admin',
              'venv.lib.python3.6.site-packages.django.contrib.admin.views',
              'venv.lib.python3.6.site-packages.django.contrib.admin.migrations',
              'venv.lib.python3.6.site-packages.django.contrib.admin.templatetags',
              'venv.lib.python3.6.site-packages.django.contrib.sites',
              'venv.lib.python3.6.site-packages.django.contrib.sites.migrations',
              'venv.lib.python3.6.site-packages.django.contrib.humanize',
              'venv.lib.python3.6.site-packages.django.contrib.humanize.templatetags',
              'venv.lib.python3.6.site-packages.django.contrib.messages',
              'venv.lib.python3.6.site-packages.django.contrib.messages.storage',
              'venv.lib.python3.6.site-packages.django.contrib.postgres',
              'venv.lib.python3.6.site-packages.django.contrib.postgres.forms',
              'venv.lib.python3.6.site-packages.django.contrib.postgres.fields',
              'venv.lib.python3.6.site-packages.django.contrib.postgres.aggregates',
              'venv.lib.python3.6.site-packages.django.contrib.sessions',
              'venv.lib.python3.6.site-packages.django.contrib.sessions.backends',
              'venv.lib.python3.6.site-packages.django.contrib.sessions.migrations',
              'venv.lib.python3.6.site-packages.django.contrib.sitemaps',
              'venv.lib.python3.6.site-packages.django.contrib.admindocs',
              'venv.lib.python3.6.site-packages.django.contrib.flatpages',
              'venv.lib.python3.6.site-packages.django.contrib.flatpages.migrations',
              'venv.lib.python3.6.site-packages.django.contrib.flatpages.templatetags',
              'venv.lib.python3.6.site-packages.django.contrib.redirects',
              'venv.lib.python3.6.site-packages.django.contrib.redirects.migrations',
              'venv.lib.python3.6.site-packages.django.contrib.staticfiles',
              'venv.lib.python3.6.site-packages.django.contrib.staticfiles.templatetags',
              'venv.lib.python3.6.site-packages.django.contrib.syndication',
              'venv.lib.python3.6.site-packages.django.contrib.contenttypes',
              'venv.lib.python3.6.site-packages.django.contrib.contenttypes.management',
              'venv.lib.python3.6.site-packages.django.contrib.contenttypes.migrations',
              'venv.lib.python3.6.site-packages.django.dispatch', 'venv.lib.python3.6.site-packages.django.template',
              'venv.lib.python3.6.site-packages.django.template.loaders',
              'venv.lib.python3.6.site-packages.django.template.backends',
              'venv.lib.python3.6.site-packages.django.middleware',
              'venv.lib.python3.6.site-packages.django.templatetags', 'venv.lib.python3.6.site-packages.pandas',
              'venv.lib.python3.6.site-packages.pandas.io', 'venv.lib.python3.6.site-packages.pandas.io.sas',
              'venv.lib.python3.6.site-packages.pandas.io.json', 'venv.lib.python3.6.site-packages.pandas.io.formats',
              'venv.lib.python3.6.site-packages.pandas.io.msgpack',
              'venv.lib.python3.6.site-packages.pandas.io.clipboard', 'venv.lib.python3.6.site-packages.pandas.api',
              'venv.lib.python3.6.site-packages.pandas.api.types',
              'venv.lib.python3.6.site-packages.pandas.api.extensions', 'venv.lib.python3.6.site-packages.pandas.core',
              'venv.lib.python3.6.site-packages.pandas.core.util', 'venv.lib.python3.6.site-packages.pandas.core.tools',
              'venv.lib.python3.6.site-packages.pandas.core.arrays',
              'venv.lib.python3.6.site-packages.pandas.core.dtypes',
              'venv.lib.python3.6.site-packages.pandas.core.sparse',
              'venv.lib.python3.6.site-packages.pandas.core.groupby',
              'venv.lib.python3.6.site-packages.pandas.core.indexes',
              'venv.lib.python3.6.site-packages.pandas.core.reshape',
              'venv.lib.python3.6.site-packages.pandas.core.computation',
              'venv.lib.python3.6.site-packages.pandas.util', 'venv.lib.python3.6.site-packages.pandas._libs',
              'venv.lib.python3.6.site-packages.pandas._libs.tslibs', 'venv.lib.python3.6.site-packages.pandas.tests',
              'venv.lib.python3.6.site-packages.pandas.tests.io',
              'venv.lib.python3.6.site-packages.pandas.tests.io.sas',
              'venv.lib.python3.6.site-packages.pandas.tests.io.json',
              'venv.lib.python3.6.site-packages.pandas.tests.io.parser',
              'venv.lib.python3.6.site-packages.pandas.tests.io.formats',
              'venv.lib.python3.6.site-packages.pandas.tests.io.msgpack',
              'venv.lib.python3.6.site-packages.pandas.tests.api', 'venv.lib.python3.6.site-packages.pandas.tests.util',
              'venv.lib.python3.6.site-packages.pandas.tests.frame',
              'venv.lib.python3.6.site-packages.pandas.tests.tools',
              'venv.lib.python3.6.site-packages.pandas.tests.dtypes',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar.period',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar.interval',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar.timedelta',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar.timestamp',
              'venv.lib.python3.6.site-packages.pandas.tests.series',
              'venv.lib.python3.6.site-packages.pandas.tests.series.indexing',
              'venv.lib.python3.6.site-packages.pandas.tests.sparse',
              'venv.lib.python3.6.site-packages.pandas.tests.sparse.frame',
              'venv.lib.python3.6.site-packages.pandas.tests.sparse.series',
              'venv.lib.python3.6.site-packages.pandas.tests.tslibs',
              'venv.lib.python3.6.site-packages.pandas.tests.generic',
              'venv.lib.python3.6.site-packages.pandas.tests.groupby',
              'venv.lib.python3.6.site-packages.pandas.tests.groupby.aggregate',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes.period',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes.interval',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes.datetimes',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes.timedeltas',
              'venv.lib.python3.6.site-packages.pandas.tests.reshape',
              'venv.lib.python3.6.site-packages.pandas.tests.reshape.merge',
              'venv.lib.python3.6.site-packages.pandas.tests.tseries',
              'venv.lib.python3.6.site-packages.pandas.tests.tseries.offsets',
              'venv.lib.python3.6.site-packages.pandas.tests.indexing',
              'venv.lib.python3.6.site-packages.pandas.tests.indexing.interval',
              'venv.lib.python3.6.site-packages.pandas.tests.plotting',
              'venv.lib.python3.6.site-packages.pandas.tests.extension',
              'venv.lib.python3.6.site-packages.pandas.tests.extension.base',
              'venv.lib.python3.6.site-packages.pandas.tests.extension.json',
              'venv.lib.python3.6.site-packages.pandas.tests.extension.decimal',
              'venv.lib.python3.6.site-packages.pandas.tests.extension.category',
              'venv.lib.python3.6.site-packages.pandas.tests.internals',
              'venv.lib.python3.6.site-packages.pandas.tests.categorical',
              'venv.lib.python3.6.site-packages.pandas.tests.computation',
              'venv.lib.python3.6.site-packages.pandas.tools', 'venv.lib.python3.6.site-packages.pandas.types',
              'venv.lib.python3.6.site-packages.pandas.compat', 'venv.lib.python3.6.site-packages.pandas.compat.numpy',
              'venv.lib.python3.6.site-packages.pandas.errors', 'venv.lib.python3.6.site-packages.pandas.formats',
              'venv.lib.python3.6.site-packages.pandas.tseries', 'venv.lib.python3.6.site-packages.pandas.plotting',
              'venv.lib.python3.6.site-packages.pandas.computation', 'venv.lib.python3.6.site-packages.IPython',
              'venv.lib.python3.6.site-packages.IPython.lib', 'venv.lib.python3.6.site-packages.IPython.lib.tests',
              'venv.lib.python3.6.site-packages.IPython.core', 'venv.lib.python3.6.site-packages.IPython.core.tests',
              'venv.lib.python3.6.site-packages.IPython.core.magics', 'venv.lib.python3.6.site-packages.IPython.utils',
              'venv.lib.python3.6.site-packages.IPython.utils.tests', 'venv.lib.python3.6.site-packages.IPython.kernel',
              'venv.lib.python3.6.site-packages.IPython.testing',
              'venv.lib.python3.6.site-packages.IPython.testing.tests',
              'venv.lib.python3.6.site-packages.IPython.testing.plugin',
              'venv.lib.python3.6.site-packages.IPython.external',
              'venv.lib.python3.6.site-packages.IPython.external.decorators',
              'venv.lib.python3.6.site-packages.IPython.terminal',
              'venv.lib.python3.6.site-packages.IPython.terminal.tests',
              'venv.lib.python3.6.site-packages.IPython.terminal.pt_inputhooks',
              'venv.lib.python3.6.site-packages.IPython.sphinxext',
              'venv.lib.python3.6.site-packages.IPython.extensions',
              'venv.lib.python3.6.site-packages.IPython.extensions.tests', 'venv.lib.python3.6.site-packages.pexpect',
              'venv.lib.python3.6.site-packages.sklearn', 'venv.lib.python3.6.site-packages.sklearn.svm',
              'venv.lib.python3.6.site-packages.sklearn.svm.tests', 'venv.lib.python3.6.site-packages.sklearn.tree',
              'venv.lib.python3.6.site-packages.sklearn.tree.tests', 'venv.lib.python3.6.site-packages.sklearn.tests',
              'venv.lib.python3.6.site-packages.sklearn.utils', 'venv.lib.python3.6.site-packages.sklearn.utils.tests',
              'venv.lib.python3.6.site-packages.sklearn.utils.sparsetools',
              'venv.lib.python3.6.site-packages.sklearn.utils.sparsetools.tests',
              'venv.lib.python3.6.site-packages.sklearn.cluster',
              'venv.lib.python3.6.site-packages.sklearn.cluster.tests',
              'venv.lib.python3.6.site-packages.sklearn.metrics',
              'venv.lib.python3.6.site-packages.sklearn.metrics.tests',
              'venv.lib.python3.6.site-packages.sklearn.metrics.cluster',
              'venv.lib.python3.6.site-packages.sklearn.metrics.cluster.tests',
              'venv.lib.python3.6.site-packages.sklearn.mixture',
              'venv.lib.python3.6.site-packages.sklearn.mixture.tests',
              'venv.lib.python3.6.site-packages.sklearn.datasets',
              'venv.lib.python3.6.site-packages.sklearn.datasets.tests',
              'venv.lib.python3.6.site-packages.sklearn.ensemble',
              'venv.lib.python3.6.site-packages.sklearn.ensemble.tests',
              'venv.lib.python3.6.site-packages.sklearn.manifold',
              'venv.lib.python3.6.site-packages.sklearn.manifold.tests',
              'venv.lib.python3.6.site-packages.sklearn.externals',
              'venv.lib.python3.6.site-packages.sklearn.externals.joblib',
              'venv.lib.python3.6.site-packages.sklearn.neighbors',
              'venv.lib.python3.6.site-packages.sklearn.neighbors.tests',
              'venv.lib.python3.6.site-packages.sklearn.covariance',
              'venv.lib.python3.6.site-packages.sklearn.covariance.tests',
              'venv.lib.python3.6.site-packages.sklearn._build_utils',
              'venv.lib.python3.6.site-packages.sklearn.linear_model',
              'venv.lib.python3.6.site-packages.sklearn.linear_model.tests',
              'venv.lib.python3.6.site-packages.sklearn.__check_build',
              'venv.lib.python3.6.site-packages.sklearn.decomposition',
              'venv.lib.python3.6.site-packages.sklearn.decomposition.tests',
              'venv.lib.python3.6.site-packages.sklearn.preprocessing',
              'venv.lib.python3.6.site-packages.sklearn.preprocessing.tests',
              'venv.lib.python3.6.site-packages.sklearn.neural_network',
              'venv.lib.python3.6.site-packages.sklearn.neural_network.tests',
              'venv.lib.python3.6.site-packages.sklearn.model_selection',
              'venv.lib.python3.6.site-packages.sklearn.model_selection.tests',
              'venv.lib.python3.6.site-packages.sklearn.semi_supervised',
              'venv.lib.python3.6.site-packages.sklearn.semi_supervised.tests',
              'venv.lib.python3.6.site-packages.sklearn.gaussian_process',
              'venv.lib.python3.6.site-packages.sklearn.gaussian_process.tests',
              'venv.lib.python3.6.site-packages.sklearn.feature_selection',
              'venv.lib.python3.6.site-packages.sklearn.feature_selection.tests',
              'venv.lib.python3.6.site-packages.sklearn.feature_extraction',
              'venv.lib.python3.6.site-packages.sklearn.feature_extraction.tests',
              'venv.lib.python3.6.site-packages.sklearn.cross_decomposition',
              'venv.lib.python3.6.site-packages.sklearn.cross_decomposition.tests',
              'venv.lib.python3.6.site-packages.wcwidth', 'venv.lib.python3.6.site-packages.wcwidth.tests',
              'venv.lib.python3.6.site-packages.backcall', 'venv.lib.python3.6.site-packages.dateutil',
              'venv.lib.python3.6.site-packages.dateutil.tz', 'venv.lib.python3.6.site-packages.dateutil.parser',
              'venv.lib.python3.6.site-packages.dateutil.zoneinfo', 'venv.lib.python3.6.site-packages.psycopg2',
              'venv.lib.python3.6.site-packages.psycopg2.tests', 'venv.lib.python3.6.site-packages.pygments',
              'venv.lib.python3.6.site-packages.pygments.lexers', 'venv.lib.python3.6.site-packages.pygments.styles',
              'venv.lib.python3.6.site-packages.pygments.filters',
              'venv.lib.python3.6.site-packages.pygments.formatters', 'venv.lib.python3.6.site-packages.packaging',
              'venv.lib.python3.6.site-packages.traitlets', 'venv.lib.python3.6.site-packages.traitlets.tests',
              'venv.lib.python3.6.site-packages.traitlets.utils',
              'venv.lib.python3.6.site-packages.traitlets.utils.tests',
              'venv.lib.python3.6.site-packages.traitlets.config',
              'venv.lib.python3.6.site-packages.traitlets.config.tests', 'venv.lib.python3.6.site-packages.matplotlib',
              'venv.lib.python3.6.site-packages.matplotlib.tri', 'venv.lib.python3.6.site-packages.matplotlib.axes',
              'venv.lib.python3.6.site-packages.matplotlib.cbook', 'venv.lib.python3.6.site-packages.matplotlib.style',
              'venv.lib.python3.6.site-packages.matplotlib.tests', 'venv.lib.python3.6.site-packages.matplotlib.compat',
              'venv.lib.python3.6.site-packages.matplotlib.testing',
              'venv.lib.python3.6.site-packages.matplotlib.testing._nose',
              'venv.lib.python3.6.site-packages.matplotlib.testing._nose.plugins',
              'venv.lib.python3.6.site-packages.matplotlib.testing.jpl_units',
              'venv.lib.python3.6.site-packages.matplotlib.backends',
              'venv.lib.python3.6.site-packages.matplotlib.backends.qt_editor',
              'venv.lib.python3.6.site-packages.matplotlib.sphinxext',
              'venv.lib.python3.6.site-packages.matplotlib.sphinxext.tests',
              'venv.lib.python3.6.site-packages.matplotlib.projections', 'venv.lib.python3.6.site-packages.pip_review',
              'venv.lib.python3.6.site-packages.ptyprocess', 'venv.lib.python3.6.site-packages.setuptools',
              'venv.lib.python3.6.site-packages.setuptools.extern',
              'venv.lib.python3.6.site-packages.setuptools._vendor',
              'venv.lib.python3.6.site-packages.setuptools._vendor.packaging',
              'venv.lib.python3.6.site-packages.setuptools.command', 'venv.lib.python3.6.site-packages.corsheaders',
              'venv.lib.python3.6.site-packages.mpl_toolkits.tests',
              'venv.lib.python3.6.site-packages.mpl_toolkits.mplot3d',
              'venv.lib.python3.6.site-packages.mpl_toolkits.axes_grid',
              'venv.lib.python3.6.site-packages.mpl_toolkits.axes_grid1',
              'venv.lib.python3.6.site-packages.mpl_toolkits.axisartist',
              'venv.lib.python3.6.site-packages.pkg_resources', 'venv.lib.python3.6.site-packages.pkg_resources.extern',
              'venv.lib.python3.6.site-packages.pkg_resources._vendor',
              'venv.lib.python3.6.site-packages.pkg_resources._vendor.packaging',
              'venv.lib.python3.6.site-packages.prompt_toolkit',
              'venv.lib.python3.6.site-packages.prompt_toolkit.layout',
              'venv.lib.python3.6.site-packages.prompt_toolkit.styles',
              'venv.lib.python3.6.site-packages.prompt_toolkit.contrib',
              'venv.lib.python3.6.site-packages.prompt_toolkit.contrib.telnet',
              'venv.lib.python3.6.site-packages.prompt_toolkit.contrib.completers',
              'venv.lib.python3.6.site-packages.prompt_toolkit.contrib.validators',
              'venv.lib.python3.6.site-packages.prompt_toolkit.contrib.regular_languages',
              'venv.lib.python3.6.site-packages.prompt_toolkit.filters',
              'venv.lib.python3.6.site-packages.prompt_toolkit.terminal',
              'venv.lib.python3.6.site-packages.prompt_toolkit.clipboard',
              'venv.lib.python3.6.site-packages.prompt_toolkit.eventloop',
              'venv.lib.python3.6.site-packages.prompt_toolkit.key_binding',
              'venv.lib.python3.6.site-packages.prompt_toolkit.key_binding.bindings',
              'venv.lib.python3.6.site-packages.ipython_genutils',
              'venv.lib.python3.6.site-packages.ipython_genutils.tests',
              'venv.lib.python3.6.site-packages.ipython_genutils.testing',
              'venv.lib.python3.6.site-packages.django_extensions',
              'venv.lib.python3.6.site-packages.django_extensions.db',
              'venv.lib.python3.6.site-packages.django_extensions.db.fields',
              'venv.lib.python3.6.site-packages.django_extensions.jobs',
              'venv.lib.python3.6.site-packages.django_extensions.jobs.daily',
              'venv.lib.python3.6.site-packages.django_extensions.jobs.hourly',
              'venv.lib.python3.6.site-packages.django_extensions.jobs.weekly',
              'venv.lib.python3.6.site-packages.django_extensions.jobs.yearly',
              'venv.lib.python3.6.site-packages.django_extensions.jobs.monthly',
              'venv.lib.python3.6.site-packages.django_extensions.jobs.minutely',
              'venv.lib.python3.6.site-packages.django_extensions.admin',
              'venv.lib.python3.6.site-packages.django_extensions.utils',
              'venv.lib.python3.6.site-packages.django_extensions.logging',
              'venv.lib.python3.6.site-packages.django_extensions.mongodb',
              'venv.lib.python3.6.site-packages.django_extensions.mongodb.fields',
              'venv.lib.python3.6.site-packages.django_extensions.management',
              'venv.lib.python3.6.site-packages.django_extensions.management.commands',
              'venv.lib.python3.6.site-packages.django_extensions.templatetags', 'ouvidoMusical',
              'ouvidoMusical.local'],
    url='',
    license='MIT',
    author='Diego Corrêa da Silva',
    author_email='diegocorrea.cc@gmail.com',
    description='A server-side music recommendation system'
)
