# Generated by Django 2.1 on 2018-08-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(db_index=True, default='024f4323a01911e88469a6c2a045979d', max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
