# Generated by Django 2.1 on 2018-08-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(db_index=True, default='560250239f5611e88206b79ed662db35', max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
