# Generated by Django 2.1 on 2018-08-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180818_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(db_index=True, default='d8b9cdcba32e11e8bcc87fa34c60b1da', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
