# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songCompare', models.CharField(max_length=255)),
                ('similarity', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song', models.CharField(db_index=True, default='9790bd8499db11e79622708bcdd0cf1e', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('year', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.CharField(db_index=True, default='9790bd8599db11e79622708bcdd0cf1e', max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlaySong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_count', models.IntegerField(default=0)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserSongRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilit_play_count', models.IntegerField(default=0)),
                ('iLike', models.BooleanField(default=False)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.AddField(
            model_name='itemsimilarity',
            name='songBase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Song'),
        ),
    ]
