# Generated by Django 2.1 on 2018-08-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='created_at',
        ),
    ]
