# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(db_index=True, default='f748d4b8b07011e7aa05708bcdd0cf1e', max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
