# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(db_index=True, default=b'354a9beaa06611e7b972708bcdd0cf1e', max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
