# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171016_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(db_index=True, default='2fdf32a6b28611e798f8708bcdd0cf1e', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
