# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171201_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(db_index=True, default='e5983cdcd79811e7baff708bcdd0cf1e', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
