# Generated by Django 2.1 on 2018-09-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_set_size', models.IntegerField()),
                ('user_set_size', models.IntegerField()),
                ('metadata_used', models.CharField(max_length=511)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
            ],
        ),
    ]
