# Generated by Django 2.1 on 2018-08-18 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAverageLife',
            new_name='Round',
        ),
    ]
