# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20180106_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.CharField(db_index=True, default='2bd9a6aaf2a511e7a4d2708bcdd0cf1e', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
