# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-12 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20180129_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.CharField(db_index=True, default='df4034d4558d11e89706310a4b140218', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
