# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20180112_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.CharField(db_index=True, default='170c7a86f7b911e7b7a9708bcdd0cf1e', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
