# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20180116_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.CharField(db_index=True, default='729cf0f0fa7611e7adcc708bcdd0cf1e', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
