# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-21 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_auto_20180121_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.CharField(db_index=True, default='8f38a7c6fe5011e786a0708bcdd0cf1e', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
