# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-21 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userPlaySong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplaysong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song', to='songs.Song'),
        ),
    ]
