# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.CharField(db_index=True, default='70e78c11c01b11e79dc3708bcdd0cf1e', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='songsimilarity',
            name='songBase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SongSimilarity_right', to='songs.Song'),
        ),
        migrations.AlterField(
            model_name='songsimilarity',
            name='songCompare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SongSimilarity_left', to='songs.Song'),
        ),
    ]
