# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20171014_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.CharField(db_index=True, default='afd72c77b28511e798f8708bcdd0cf1e', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
