# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20171201_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.CharField(db_index=True, default='b566c44fd6d411e7baff708bcdd0cf1e', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
