# Generated by Django 2.1 on 2018-08-04 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosineSimilarity_SongTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('songBase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CosineSimilarity_SongTitle_right', to='songs.Song')),
                ('songCompare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CosineSimilarity_SongTitle_left', to='songs.Song')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cosinesimilarity_songtitle',
            unique_together={('songBase', 'songCompare')},
        ),
    ]
