# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosineSimilarity_SongTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('songBase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CosineSimilarity_SongTitle_right', to='songs.Song')),
                ('songCompare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CosineSimilarity_SongTitle_left', to='songs.Song')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cosinesimilarity_songtitle',
            unique_together=set([('songBase', 'songCompare')]),
        ),
    ]
