# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosinesimilarity_songtitle',
            name='updated_at',
        ),
    ]
