# Generated by Django 2.1 on 2018-08-14 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userAverange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAverageRunTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_model_size', models.IntegerField()),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('life', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userAverange.UserAverageLife')),
            ],
        ),
    ]
