# Generated by Django 2.1 on 2018-09-09 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAverageRunTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_set_size', models.IntegerField()),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='round.Round')),
            ],
        ),
    ]
