# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(db_index=True, default='8e4dfe09fff211e7aebd708bcdd0cf1e', max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
