# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180126_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(db_index=True, default='41038d7b03e911e89896708bcdd0cf1e', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
