# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-14 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180513_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(db_index=True, default='5fb7044d571b11e881f2b9463adf3ccc', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
