# Generated by Django 2.1 on 2018-08-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180804_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(db_index=True, default='227ec147977b11e89383c569513f40c7', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
