# Kernel Threads
MAX_THREAD = 3

SONG_MODEL_SIZE_LIST = [150, 300, 450]
RECOMMENDATION_LIST_SIZE = 10

TOTAL_RUN = 15
START_VALIDE_RUN = 5
INTERVAL = 10

AT_LIST = [1, 3, 5, 10]

MAX_SCORE = 3
MIN_SCORE = 0

GRAPH_SET_COLORS_LIST = ['red', 'green', 'blue', 'yellow']
