# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-13 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAverange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraverage_life',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
