# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAverange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraverage_recommendations',
            name='similarity',
            field=models.FloatField(default=0.0),
        ),
    ]
