# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-14 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAverange', '0002_useraverage_life_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraverage_life',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
