# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userSongRecommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersongrecommendations',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usersongrecommendations',
            name='similarity',
            field=models.FloatField(default=0.0),
        ),
    ]
