# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171016_1528'),
        ('songs', '0005_auto_20171016_1528'),
        ('userSongRecommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersongrecommendation',
            unique_together=set([('user', 'song')]),
        ),
    ]
