# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userSongRecommendation', '0002_auto_20171006_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersongrecommendation',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
