# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.CharField(db_index=True, default=b'd367b30e851711e78a794c0f6e2da75d', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(db_index=True, default=b'd367b30f851711e78a794c0f6e2da75d', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
