# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songCompare', models.CharField(max_length=255)),
                ('similarity', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.CharField(db_index=True, default=b'68a491da85db11e7a031708bcdd0cf1e', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(db_index=True, default=b'68a491db85db11e7a031708bcdd0cf1e', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='itemsimilarity',
            name='songBase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.Song'),
        ),
    ]
