# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.CharField(db_index=True, default=b'b3493c6a8d7c11e7a6e0708bcdd0cf1e', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(db_index=True, default=b'b3493c6b8d7c11e7a6e0708bcdd0cf1e', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
