# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_auto_20170820_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.CharField(db_index=True, default=b'995e9d108aaf11e7b1274c0f6e2da75d', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(db_index=True, default=b'995e9d118aaf11e7b1274c0f6e2da75d', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='itemsimilarity',
            unique_together=set([('songBase', 'songCompare')]),
        ),
        migrations.AlterUniqueTogether(
            name='usersongrecommendation',
            unique_together=set([('user', 'song')]),
        ),
    ]
