# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_auto_20170831_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.CharField(db_index=True, default=b'c4835ffc8e4d11e7a6e0708bcdd0cf1e', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(db_index=True, default=b'c4835ffd8e4d11e7a6e0708bcdd0cf1e', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
