# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_auto_20170902_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.CharField(db_index=True, default=b'9fe22278902d11e7a03f4c0f6e2da75d', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(db_index=True, default=b'9fe22279902d11e7a03f4c0f6e2da75d', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
